# Generated by Django 5.1.2 on 2024-10-09 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
